apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
      - name: zoo1
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181
        # env:
        # - name: ZOOKEEPER_ID
        #   value: "1"
        # - name: ZOOKEEPER_SERVER_1
        #   value: zoo1

---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  type: NodePort
  selector:
    app: zookeeper-1
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 3181
      targetPort: 2181
  # - name: client
  #   port: 2181
  #   protocol: TCP
  # - name: follower
  #   port: 2888
  #   protocol: TCP
  # - name: leader
  #   port: 3888
  #   protocol: TCP

